% This script run all the Figures of the paper Deep Optics Preconditioner 
%for Enhanced Pyramid Wavefront Sensing
% Felipe Guzman

Figure4A_ComputePlot
Figure4B_ComputePlot
Figure5_ComputePlot
Figure6A_ComputePlot
Figure6B_ComputePlot
Figure7_ComputePlot
Figure8A_ComputePlot
Figure8B_ComputePlot
Figure9_ComputePlot
Figure10A_ComputePlot
Figure10B_ComputePlot
Figure11_ComputePlot